import streamlit as st
import pandas as pd
import numpy as np
import joblib

# input dict for categorical label
# brand dict
country = {
 'Canada': 0,
'United States': 1,
'Ireland': 2,
'China': 3,
'France': 4,
'United Kingdom': 5,
'Iran, Islamic Republic of': 6,
'Russian Federation': 7,
'India': 8,
'Japan': 9,
'Germany': 10,
'Argentina': 11,
'Nicaragua': 12,
'Ghana': 13,
'Italy': 14,
'Australia': 15,
'Spain': 16,
'Malaysia': 17,
'Israel': 18,
'Ukraine': 19,
'Netherlands': 20,
'Puerto Rico': 21,
'Portugal': 22,
'Iraq': 23,
'New Zealand': 24,
'Hungary': 25,
'Greece': 26,
'Lithuania': 27,
'Norway': 28,
'Cuba': 29,
'Austria': 30,
'South Africa': 31,
'Czech Republic': 32,
'Philippines': 33,
'Ethiopia': 34,
'Mexico': 35,
'Turkey': 36,
'Croatia': 37,
'Uruguay': 38,
'Sri Lanka': 39,
'Poland': 40,
'Egypt': 41,
'Venezuela': 42,
'Brazil': 43,
'Kenya': 44,
'Serbia': 45,
'Bosnia and Herzegovina': 46,
'Peru': 47,
'Nepal': 48,
'Belgium': 49,
'Syrian Arab Republic': 50,
'Nigeria': 51,
'El Salvador': 52,
'Paraguay': 53,
'Saudi Arabia': 54,
'Sweden': 55,
'Estonia': 56,
'Romania': 57,
'Papua New Guinea': 58,
'Colombia': 59,
'Switzerland': 60,
'Chile': 61,
'Azerbaijan': 62,
'Tajikistan': 63,
'Finland': 64,
'Denmark': 65,
'Namibia': 66,
'Togo': 67,
'Indonesia': 68,
'Ecuador': 69,
'Slovenia': 70,
'Belarus': 71,
"Korea, Democratic People's": 72,
'Albania': 73,
'Singapore': 74,
'Madagascar': 75,
'Uzbekistan': 76,
'Pakistan': 77,
'Gabon': 78,
'Congo, The Democratic Republic of the': 79,
'Netherlands Antilles': 80,
'Jamaica': 81,
'Haiti': 82,
'Afghanistan': 83,
'Iceland': 84,
'Tunisia': 85,
'Bulgaria': 86,
'Somalia': 87,
'Guatemala': 88,
'Chad': 89,
'Panama': 90,
'Macedonia, The Former Yugoslav': 91,
'Bolivia': 92,
'Trinidad and Tobago': 93,
'Lebanon': 94,
'Bangladesh': 95,
'Guyana': 96,
'Cyprus': 97,
'Costa Rica': 98,
'Georgia': 99,
'Kiribati': 100,
'Malta': 101,
'Armenia': 102,
'Mauritania': 103,
'Morocco': 104,
'Cambodia': 105,
'Honduras': 106,
'Zambia': 107,
'Algeria': 108,
'Sudan': 109,
'United Arab Emirates': 110,
'Kazakhstan': 111,
'Eritrea': 112,
'Liberia': 113,
'Thailand': 114,
'Bermuda': 115,
'Dominican Republic': 116,
'Slovakia': 117,
'Bahrain': 118,
'Cook Islands': 119,
'Latvia': 120,
'Saint Kitts and Nevis': 121,
'Central African Republic': 122,
'Mali': 123,
'Montenegro': 124,
'Jordan': 125,
'Equatorial Guinea': 126,
'Suriname': 127,
'Senegal': 128,
'Luxembourg': 129,
'Holy See (Vatican City State)': 130,
'Rwanda': 131,
'Cape Verde': 132,
'Dominica': 133,
'Kyrgyzstan': 134,
'San Marino': 135,
'Angola': 136,
'Moldova, Republic of': 137,
'Saint Lucia': 138,
'Yemen': 139,
'Hong Kong': 140,
'Andorra': 141,
'Micronesia, Federated States of': 142,
'Zimbabwe': 143,
'Bahamas': 144,
'Uganda': 145,
'Fiji': 146,
'Botswana': 147,
'Gibraltar': 148,
'Burundi': 149,
'Nauru': 150,
'American Samoa': 151,
'Grenada': 152,
'Mozambique': 153,
'Marshall Islands': 154,
'Malawi': 155,
'Comoros': 156,
'Burkina Faso': 157,
'Libyan Arab Jamahiriya': 158,
'Guinea': 159,
'Sierra Leone': 160,
'Jersey': 161,
'Isle of Man': 162,
'Cameroon': 163,
'Turkmenistan': 164,
'Vanuatu': 165,
'Seychelles': 166,
'Tuvalu': 167,
'Barbados': 168,
'Belize': 169,
'Aruba': 170,
'Tanzania, United Republic of': 171,
'Niger': 172,
'Western Sahara': 173,
'Monaco': 174,
'Northern Mariana Islands': 175,
'Guinea-Bissau': 176,
'Austria-Hungary': 177,
'County of Flanders': 178,
'County of Holland': 179,
'Crown of Aragón': 180,
'Crown of Castile': 181,
'Hyderabad State': 182,
'Illyrian Provinces': 183,
'Korea, Republic of': 184,
'Ottoman Empire': 185,
'Palestinian Territory,Occupied': 186,
'Polish–Lithuanian Commonwealth': 187,
'Rhodesia': 188,
'Russia': 189,
'Seleucid Empire': 190,
'Serbia and Montenegro': 191,
'Serbian Grand Principality': 192,
'Seventeen Provinces': 193,
'Slovak State (1939-1945)': 194,
'South African Republic': 195,
'Umayyad Caliphate': 196,
'Viet Nam': 197,
'Yugoslavia': 198,   
}

# model dict
occ = {
'politician': 0,
'artist': 1,
'truck driver': 2,
'spree killer': 3,
'journalist': 4,
'researcher': 5,
'athlete': 6,
'businessperson': 7,
'military personnel': 8,
'television presenter': 9,
'radio personality': 10,
'engineer': 11,
'choreographer': 12,
'entrepreneur': 13,
'gastroenterologist': 14,
'nascar team owner': 15,
'serial killer': 16,
'criminal': 17,
'translator': 18,
'dentist': 19,
'presbyter': 20,
'farmer': 21,
'socialite': 22,
'midwife': 23,
'religious figure': 24,
'ichthyologist': 25,
'teacher': 26,
'business executive': 27,
'scenographer': 28,
'aristocrat': 29,
'jockey': 30,
'rapper': 31,
'professional wrestler': 32,
'guitarist': 33,
'philosopher': 34,
'explorer': 35,
'graphic designer': 36,
'architect': 37,
'resistance fighter': 38,
'interpreter': 39,
'construction worker': 40,
'business magnate': 41,
'drummer': 42,
'nurse': 43,
'torturer': 44,
'concentration camp guard': 45,
'biologist': 46,
'academic': 47,
'capo dei capi': 48,
'designer': 49,
'cinematographer': 50,
'philanthropist': 51,
'barrister': 52,
'talent manager': 53,
'talent agent': 54,
'manager': 55,
'dancer': 56,
'christians jehovah’s witnesses': 57,
'dermatologist': 58,
'professeur des universités – praticien hospitalier': 59,
'film producer': 60,
'psychologist': 61,
'puppeteer': 62,
'terrorist': 63,
'jihadist': 64,
'nun': 65,
'animator': 66,
'animation director': 67,
'monk': 68,
'dietitian': 69,
'bodybuilder': 70,
'racing automobile driver': 71,
'formula one driver': 72,
'camera operator': 73,
'orientalist': 74,
'preacher': 75,
'gangster': 76,
'drug trafficker': 77,
'religious leader': 78,
'samurai': 79,
'judge': 80,
'chef': 81,
'motorcycle racer': 82,
'cardiologist': 83,
'student': 84,
'amateur wrestler': 85,
'judoka': 86,
'biographer': 87,
'mechanic': 88,
'park ranger': 89,
'monarch': 90,
'record producer': 91,
'entertainer': 92,
'balloonist': 93,
'skateboarder': 94,
'psychiatrist': 95,
'cook': 96,
'activist': 97,
'pupil': 98,
'trade unionist': 99,
'mountaineer': 100,
'fencer': 101,
'playwright': 102,
'author': 103,
'novelist': 104,
'racing driver': 105,
'creator': 106,
'publisher': 107,
'fashion designer': 108,
'magician': 109,
'radio operator': 110,
'spy': 111,
'rower': 112,
'announcer': 113,
'statistician': 114,
'combat medic': 115,
'physician': 116,
'game designer': 117,
'programmer': 118,
'immunologist': 119,
'obstetrician': 120,
'alpine skier': 121,
'feminist': 122,
'comedian': 123,
'astronomer': 124,
'erudite': 125,
'saxophonist': 126,
'circus performer': 127,
'lawyer': 128,
'flying ace': 129,
'anatomist': 130,
'magistrate': 131,
'model': 132,
'insurance broker': 133,
'bookseller': 134,
'librarian': 135,
'referee': 136,
'beauty pageant contestant': 137,
'conductor': 138,
'music director': 139,
'waste collector': 140,
'typographer': 141,
'drawer': 142,
'gallerist': 143,
'human rights activist': 144,
'organist': 145,
'flight attendant': 146,
'documentary filmmaker': 147,
'marine biologist': 148,
'sailor': 149,
'philosopher of science': 150,
'secret service agent': 151,
'submariner': 152,
'cartographer': 153,
'investment banker': 154,
'religious servant': 155,
'airman': 156,
'geographer': 157,
'civil servant': 158,
'art dealer': 159,
'freestyle skier': 160,
'police officer': 161,
'flautist': 162,
'pianist': 163,
'colonial administrator': 164,
'weightlifter': 165,
'servant of god': 166,
'restaurateur': 167,
'mangaka': 168,
'propagandist': 169,
'anarchist': 170,
'chartered certified accountant': 171,
'conquistador': 172,
'condottiero': 173,
'geneticist': 174,
'tool and die maker': 175,
'broadcast programming director': 176,
'gendarme': 177,
'intelligence analyst': 178,
'salonnière': 179,
'civil guard (spain)': 180,
'jurist': 181,
'concertmaster': 182,
'violinist': 183,
'disc jockey': 184,
'numismatist': 185,
'coxswain': 186,
'organized crime': 187,
'lottery': 188,
'numbers game': 189,
'murderer': 190,
'surgeon': 191,
'ophthalmologist': 192,
'armenologist': 193,
'sovereign': 194,
'music producer': 195,
'essayist': 196,
'pedagogue': 197,
'production designer': 198,
'nutritionist': 199,
'accountant': 200,
'surfer': 201,
'skier': 202,
'blogger': 203,
'bullfighter': 204,
'astrologer': 205,
'geodesist': 206,
'fighter pilot': 207,
'art director': 208,
'marathon runner': 209,
'violist': 210,
'mercenary': 211,
'art collector': 212,
'hammer thrower': 213,
'prostitute': 214,
'contract killer': 215,
'farmworker': 216,
'naval officer': 217,
'revolutionary': 218,
'cellist': 219,
'nan': 220,
'martyr': 221,
'officer of the french navy': 222,
'regent': 223,
'prosecutor': 224,
'humanitarian': 225,
'hurdler': 226,
'powerlifter': 227,
'sound designer': 228,
'internist': 229,
'television director': 230,
'laborer': 231,
'intelligence officer': 232,
'model agent': 233,
'pharmacist': 234,
'privateer': 235,
'pirate': 236,
'mason': 237,
'banjoist': 238,
'navigator': 239,
'investor': 240,
'worker': 241,
'playboy playmate': 242,
'banker': 243,
'waiter': 244,
'music pedagogue': 245,
'rikishi': 246,
'clown': 247,
'archer': 248,
'hairdresser': 249,
'vedette': 250,
'youtuber': 251,
'motivational speaker': 252,
'horticulturist': 253,
'peace activist': 254,
'guitar maker': 255,
'musical instrument maker': 256,
'bhikkhu': 257,
'firefighter': 258,
'bushi': 259,
'conscientious objection': 260,
'pacifist': 261,
'theater director': 262,
'electrician': 263,
'altar server': 264,
'inventor': 265,
'ondist': 266,
'catch trainer': 267,
'ballet dancer': 268,
'ballet master': 269,
'diarist': 270,
'security guard': 271,
'assembly line worker': 272,
'environmentalist': 273,
'political activist': 274,
'official': 275,
'first lady': 276,
'housekeeper': 277,
'psychotherapist': 278,
'prelate': 279,
'chaplain': 280,
'railroad construction foreman': 281,
'ecologist': 282,
'social worker': 283,
'social activist': 284,
'autobiographer': 285,
'editor': 286,
'game programmer': 287,
'funeral director': 288,
'curler': 289,
'sprinter': 290,
'veterinarian': 291,
'music executive': 292,
'costume designer': 293,
'karateka': 294,
'television producer': 295,
'character animator': 296,
'sound editor': 297,
'trumpeter': 298,
'columnist': 299,
'canoeist': 300,
'philologist': 301,
'choir director': 302,
'cardiac surgeon': 303,
'terrorism': 304,
'civil rights advocate': 305,
'cross-country skier': 306,
'minister': 307,
'herpetologist': 308,
'merchant': 309,
'homekeeper': 310,
'show jumper': 311,
'zookeeper': 312,
'primatologist': 313,
'horse trainer': 314,
'javelin thrower': 315,
'archivist': 316,
'paleontologist': 317,
'pathologist': 318,
'contributing editor': 319,
'art critic': 320,
'critic': 321,
'pastor': 322,
'long-distance runner': 323,
'middle-distance runner': 324,
'rancher': 325,
'drug lord': 326,
'trader': 327,
'executioner': 328,
'boatswain': 329,
'watchmaker': 330,
'car designer': 331,
'microbiologist': 332,
'virologist': 333,
'pretender': 334,
'executive': 335,
'oceanographer': 336,
'academic administrator': 337,
'pentito': 338,
'impresario': 339,
'anthropologist': 340,
'executive producer': 341,
'legal scholar': 342,
'patent inventor': 343,
'criminologist': 344,
'cowboy': 345,
'ruler': 346,
'mandolinist': 347,
'radio producer': 348,
'skipper': 349,
'sociologist': 350,
'steeplechase runner': 351,
'founder': 352,
'personal trainer': 353,
'stripper': 354,
'protestant reformer': 355,
'trombonist': 356,
'producer': 357,
'music promoter': 358,
'procurer': 359,
'carpenter': 360,
'promoter': 361,
"corps de l'armement": 362,
'technician': 363,
'financier': 364,
'rally driver': 365,
'sex worker': 366,
'lgbt rights activist': 367,
'newspaper editor': 368,
'thief': 369,
'speleologist': 370,
'handyman': 371,
'feudatory': 372,
'geheimrat': 373,
'fashion model': 374,
'diamond cutter': 375,
'curator': 376,
'bandleader': 377,
'seiy?': 378,
'illegal drug trade': 379,
'racket': 380,
'female guards in nazi concentration camps': 381,
'psychoanalyst': 382,
'french resistance fighter': 383,
'bibliographer': 384,
'rock drummer': 385,
'ceramist': 386,
'jazz pianist': 387,
'penciller': 388,
'plant physiology': 389,
'oncologist': 390,
'skydiver': 391,
'kayaker': 392,
'forensic psychiatrist': 393,
'aikidoka': 394,
'healer': 395,
'herbalist': 396,
'manual worker': 397,
'casting director': 398,
'fiddler': 399,
'triple jumper': 400,
'literary': 401,
'bassist': 402,
'baker': 403,
'organizer': 404,
'physiologist': 405,
'islamistic terrorism': 406,
'drafter': 407,
'ornithologist': 408,
'criminal sniper': 409,
'functionary': 410,
'daimyo': 411,
'abolitionist': 412,
'co-driver': 413,
'glamour model': 414,
'naturalist': 415,
'stockbroker': 416,
'combatant': 417,
'suffragette': 418,
'parson': 419,
'suffragist': 420,
'neurologist': 421,
'land agent': 422,
'rock climber': 423,
'elevator operator': 424,
'knight of the order of the temple': 425,
'bobsledder': 426,
'competitive diver': 427,
'event rider': 428,
'oboist': 429,
'imam': 430,
'clarinetist': 431,
'real estate development': 432,
'film critic': 433,
'chief executive officer': 434,
'pharmacologist': 435,
'war correspondent': 436,
'rabbi': 437,
'double-bassist': 438,
'postage stamp designer': 439,
'printmaker': 440,
'general practitioner': 441,
'luger': 442,
'fashion editor': 443,
'felony': 444,
'esperantist': 445,
'news presenter': 446,
'heilpraktiker': 447,
'snowboarder': 448,
'opera director': 449,
'correspondent': 450,
'consort': 451,
'ballet pedagogue': 452,
'highwayman': 453,
'tribal chief': 454,
'brother': 455,
'weather presenter': 456,
'mycologist': 457,
'chief of police': 458,
'scholar': 459,
'mountain guide': 460,
'classical philologist': 461,
'governess': 462,
'genealogist': 463,
'reporter': 464,
'theatrical producer': 465,
'salesperson': 466,
'chronicler': 467,
'investigative reporter': 468,
'ethologist': 469,
'game author': 470,
'criminality': 471,
'rhetorician': 472,
'dandy': 473,
'harpsichordist': 474,
'dance critic': 475,
'artisan': 476,
'puzzle designer': 477,
'lobbyist': 478,
'extortion': 479,
'blacksmith': 480,
'tailor': 481,
'mobster': 482,
'musicologist': 483,
'ethnomusicologist': 484,
'stunt performer': 485,
'epidemiologist': 486,
'paralegal': 487,
'private investigator': 488,
'secretary': 489,
'interior designer': 490,
'motocross rider': 491,
'illusionist': 492,
'harpist': 493,
'child psychiatrist': 494,
'test pilot': 495,
'cadet': 496,
'warrior': 497,
'rakugoka': 498,
'theatre manager': 499,
'music critic': 500,
'watercolourist': 501,
'flight nurse': 502,
'musher': 503,
'ski mountaineer': 504,
'lexicographer': 505,
'televangelist': 506,
'meteorologist': 507,
'notary': 508,
'volcanologist': 509,
'conservator': 510,
'breakdancer': 511,
'statesperson': 512,
'personal stylist': 513,
'bookmaker': 514,
'accordionist': 515,
'bounty hunter': 516,
'pioneer': 517,
'corvette captain': 518,
'ship captain': 519,
'maid': 520,
'lyricist': 521,
'classical guitarist': 522,
'social reformer': 523,
'base jumper': 524,
'governor': 525,
'marksman': 526,
'director': 527,
'nightclub owner': 528,
'industrialist': 529,
'sexologist': 530,
'memoirist': 531,
'quizzer': 532,
'endocrinologist': 533,
'mountain biker': 534,
'male prostitution': 535,
'militant': 536,
'latinist': 537,
'mail carrier': 538,
'matador': 539,
'metallurgist': 540,
'paratrooper': 541,
'machinist': 542,
'hotel manager': 543,
'ufologist': 544,
'ethnologist': 545,
'castellan': 546,
'butler': 547,
'joiner': 548,
'bank robber': 549,
'lady-in-waiting': 550,
'stunt pilot': 551,
'animalier': 552,
'encyclopédistes': 553,
'cleric': 554,
'law enforcement officer': 555,
'forensic pathologist': 556,
'strongman': 557,
'taxi driver': 558,
'antiquarian seller': 559,
'rhythmic gymnast': 560,
'folklorist': 561,
'stand-up comedian': 562,
'courtesan': 563,
'cobbler': 564,
'ascetic': 565,
'pro gamer': 566,
'dacoity': 567,
'museum director': 568,
'logician': 569,
'miner': 570,
'broadcaster': 571,
'literary critic': 572,
'theatre critic': 573,
'scout': 574,
'patient': 575,
'grocer': 576,
'bowler': 577,
'equestrianism': 578,
'equestrian': 579,
'rheumatologist': 580,
'dressage rider': 581,
'calligrapher': 582,
'christian mystic': 583,
'neurosurgeon': 584,
'justice of the peace': 585,
'conservationist': 586,
'go professional': 587,
'spammer': 588,
'assassin': 589,
'mujahid': 590,
'eye surgeon': 591,
'histologist': 592,
'street vendor': 593,
'collector': 594,
'winegrower': 595,
'chamberlain': 596,
'advertising person': 597,
'rapping': 598,
'heiress': 599,
'peasant': 600,
'prison warden': 601,
'optician': 602,
'bartender': 603,
'mass murder': 604,
'hurler': 605,
'bushranger': 606,
'bacteriologist': 607,
'coroner': 608,
'freemason': 609,
'stunt double': 610,
'hematologist': 611,
'soprano': 612,
'master builder': 613,
'warlord': 614,
'grand couturier': 615,
'ice dancer': 616,
'egyptologist': 617,
'habitual offender': 618,
'administrator of the government': 619,
'abbé': 620,
'bureaucrat': 621,
'psychic': 622,
'chief financial officer': 623,
'chauffeur / chauffeuse': 624,
'impostor': 625,
'lumberjack': 626,
'police': 627,
'admiral': 628,
'outlaw': 629,
'astronaut': 630,
'day trader': 631,
'air force officer': 632,
'jeweller': 633,
'intellectual': 634,
'guard': 635,
'conservation': 636,
'advocate': 637,
'orator': 638,
'stunt coordinator': 639,
'freediver': 640,
'general officer': 641,
'carabinier': 642,
'count': 643,
'presenter': 644,
'alderman': 645,
'caricaturist': 646,
'dressmaker': 647,
'production manager': 648,
'partisan': 649,
'animal rights advocate': 650,
'museum professional': 651,
"aviation boatswain's mate": 652,
'ethnographer': 653,
'court reporter': 654,
'gynaecologist': 655,
'existential therapist': 656,
'bouncer': 657,
'assessor': 658,
'miller': 659,
'fighter': 660,
'informant': 661,
'arachnologist': 662,
'sexual predator': 663,
'librettist': 664,
'carabinieri': 665,
'patron of the arts': 666,
'tutor': 667,
'rebellion': 668,
'intelligence agent': 669,
'antiquarian': 670,
'adventurer': 671,
'ballerina': 672,
'sniper': 673,
'switchboard operator': 674,
'rapist': 675,
'dissident': 676,
'political commissar': 677,
'piracy': 678,
'companion': 679,
'captain': 680,
'settler': 681,
'organ builder': 682,
'pasha': 683,
'flower seller': 684,
'crocheter': 685,
'jesuit': 686,
'art model': 687,
'lighthouse keeper': 688,
'topographer': 689,
'etcher': 690,
'engraver': 691,
'squire': 692,
'courtier': 693,
'smuggler': 694,
'fortune teller': 695,
'poisoner': 696,
'lord': 697,
'mimus': 698,
'lord of the manor': 699,
'mass murderer': 700,
'former comfort women': 701,
'apothecary': 702,
'fedayeen': 703,
'docent': 704,
'electronics technician': 705,
'witch': 706,
'bodyguard': 707,
 }

 # list of categorical label
country_list = ['Canada',
'United States',
'Ireland',
'China',
'France',
'United Kingdom',
'Iran, Islamic Republic of',
'Russian Federation',
'India',
'Japan',
'Germany',
'Argentina',
'Nicaragua',
'Ghana',
'Italy',
'Australia',
'Spain',
'Malaysia',
'Israel',
'Ukraine',
'Netherlands',
'Puerto Rico',
'Portugal',
'Iraq',
'New Zealand',
'Hungary',
'Greece',
'Lithuania',
'Norway',
'Cuba',
'Austria',
'South Africa',
'Czech Republic',
'Philippines',
'Ethiopia',
'Mexico',
'Turkey',
'Croatia',
'Uruguay',
'Sri Lanka',
'Poland',
'Egypt',
'Venezuela',
'Brazil',
'Kenya',
'Serbia',
'Bosnia and Herzegovina',
'Peru',
'Nepal',
'Belgium',
'Syrian Arab Republic',
'Nigeria',
'El Salvador',
'Paraguay',
'Saudi Arabia',
'Sweden',
'Estonia',
'Romania',
'Papua New Guinea',
'Colombia',
'Switzerland',
'Chile',
'Azerbaijan',
'Tajikistan',
'Finland',
'Denmark',
'Namibia',
'Togo',
'Indonesia',
'Ecuador',
'Slovenia',
'Belarus',
"Korea, Democratic People's",
'Albania',
'Singapore',
'Madagascar',
'Uzbekistan',
'Pakistan',
'Gabon',
'Congo, The Democratic Republic of the',
'Netherlands Antilles',
'Jamaica',
'Haiti',
'Afghanistan',
'Iceland',
'Tunisia',
'Bulgaria',
'Somalia',
'Guatemala',
'Chad',
'Panama',
'Macedonia, The Former Yugoslav',
'Bolivia',
'Trinidad and Tobago',
'Lebanon',
'Bangladesh',
'Guyana',
'Cyprus',
'Costa Rica',
'Georgia',
'Kiribati',
'Malta',
'Armenia',
'Mauritania',
'Morocco',
'Cambodia',
'Honduras',
'Zambia',
'Algeria',
'Sudan',
'United Arab Emirates',
'Kazakhstan',
'Eritrea',
'Liberia',
'Thailand',
'Bermuda',
'Dominican Republic',
'Slovakia',
'Bahrain',
'Cook Islands',
'Latvia',
'Saint Kitts and Nevis',
'Central African Republic',
'Mali',
'Montenegro',
'Jordan',
'Equatorial Guinea',
'Suriname',
'Senegal',
'Luxembourg',
'Holy See (Vatican City State)',
'Rwanda',
'Cape Verde',
'Dominica',
'Kyrgyzstan',
'San Marino',
'Angola',
'Moldova, Republic of',
'Saint Lucia',
'Yemen',
'Hong Kong',
'Andorra',
'Micronesia, Federated States of',
'Zimbabwe',
'Bahamas',
'Uganda',
'Fiji',
'Botswana',
'Gibraltar',
'Burundi',
'Nauru',
'American Samoa',
'Grenada',
'Mozambique',
'Marshall Islands',
'Malawi',
'Comoros',
'Burkina Faso',
'Libyan Arab Jamahiriya',
'Guinea',
'Sierra Leone',
'Jersey',
'Isle of Man',
'Cameroon',
'Turkmenistan',
'Vanuatu',
'Seychelles',
'Tuvalu',
'Barbados',
'Belize',
'Aruba',
'Tanzania, United Republic of',
'Niger',
'Western Sahara',
'Monaco',
'Northern Mariana Islands',
'Guinea-Bissau',
'Austria-Hungary',
'County of Flanders',
'County of Holland',
'Crown of Aragón',
'Crown of Castile',
'Hyderabad State',
'Illyrian Provinces',
'Korea, Republic of',
'Ottoman Empire',
'Palestinian Territory,Occupied',
'Polish–Lithuanian Commonwealth',
'Rhodesia',
'Russia',
'Seleucid Empire',
'Serbia and Montenegro',
'Serbian Grand Principality',
'Seventeen Provinces',
'Slovak State (1939-1945)',
'South African Republic',
'Umayyad Caliphate',
'Viet Nam',
'Yugoslavia']

# list of categorical label
occ_list = ['politician',
'artist',
'truck driver',
'spree killer',
'journalist',
'researcher',
'athlete',
'businessperson',
'military personnel',
'television presenter',
'radio personality',
'engineer',
'choreographer',
'entrepreneur',
'gastroenterologist',
'nascar team owner',
'serial killer',
'criminal',
'translator',
'dentist',
'presbyter',
'farmer',
'socialite',
'midwife',
'religious figure',
'ichthyologist',
'teacher',
'business executive',
'scenographer',
'aristocrat',
'jockey',
'rapper',
'professional wrestler',
'guitarist',
'philosopher',
'explorer',
'graphic designer',
'architect',
'resistance fighter',
'interpreter',
'construction worker',
'business magnate',
'drummer',
'nurse',
'torturer',
'concentration camp guard',
'biologist',
'academic',
'capo dei capi',
'designer',
'cinematographer',
'philanthropist',
'barrister',
'talent manager',
'talent agent',
'manager',
'dancer',
'christians jehovah’s witnesses',
'dermatologist',
'professeur des universités – praticien hospitalier',
'film producer',
'psychologist',
'puppeteer',
'terrorist',
'jihadist',
'nun',
'animator',
'animation director',
'monk',
'dietitian',
'bodybuilder',
'racing automobile driver',
'formula one driver',
'camera operator',
'orientalist',
'preacher',
'gangster',
'drug trafficker',
'religious leader',
'samurai',
'judge',
'chef',
'motorcycle racer',
'cardiologist',
'student',
'amateur wrestler',
'judoka',
'biographer',
'mechanic',
'park ranger',
'monarch',
'record producer',
'entertainer',
'balloonist',
'skateboarder',
'psychiatrist',
'cook',
'activist',
'pupil',
'trade unionist',
'mountaineer',
'fencer',
'playwright',
'author',
'novelist',
'racing driver',
'creator',
'publisher',
'fashion designer',
'magician',
'radio operator',
'spy',
'rower',
'announcer',
'statistician',
'combat medic',
'physician',
'game designer',
'programmer',
'immunologist',
'obstetrician',
'alpine skier',
'feminist',
'comedian',
'astronomer',
'erudite',
'saxophonist',
'circus performer',
'lawyer',
'flying ace',
'anatomist',
'magistrate',
'model',
'insurance broker',
'bookseller',
'librarian',
'referee',
'beauty pageant contestant',
'conductor',
'music director',
'waste collector',
'typographer',
'drawer',
'gallerist',
'human rights activist',
'organist',
'flight attendant',
'documentary filmmaker',
'marine biologist',
'sailor',
'philosopher of science',
'secret service agent',
'submariner',
'cartographer',
'investment banker',
'religious servant',
'airman',
'geographer',
'civil servant',
'art dealer',
'freestyle skier',
'police officer',
'flautist',
'pianist',
'colonial administrator',
'weightlifter',
'servant of god',
'restaurateur',
'mangaka',
'propagandist',
'anarchist',
'chartered certified accountant',
'conquistador',
'condottiero',
'geneticist',
'tool and die maker',
'broadcast programming director',
'gendarme',
'intelligence analyst',
'salonnière',
'civil guard (spain)',
'jurist',
'concertmaster',
'violinist',
'disc jockey',
'numismatist',
'coxswain',
'organized crime',
'lottery',
'numbers game',
'murderer',
'surgeon',
'ophthalmologist',
'armenologist',
'sovereign',
'music producer',
'essayist',
'pedagogue',
'production designer',
'nutritionist',
'accountant',
'surfer',
'skier',
'blogger',
'bullfighter',
'astrologer',
'geodesist',
'fighter pilot',
'art director',
'marathon runner',
'violist',
'mercenary',
'art collector',
'hammer thrower',
'prostitute',
'contract killer',
'farmworker',
'naval officer',
'revolutionary',
'cellist',
'nan',
'martyr',
'officer of the french navy',
'regent',
'prosecutor',
'humanitarian',
'hurdler',
'powerlifter',
'sound designer',
'internist',
'television director',
'laborer',
'intelligence officer',
'model agent',
'pharmacist',
'privateer',
'pirate',
'mason',
'banjoist',
'navigator',
'investor',
'worker',
'playboy playmate',
'banker',
'waiter',
'music pedagogue',
'rikishi',
'clown',
'archer',
'hairdresser',
'vedette',
'youtuber',
'motivational speaker',
'horticulturist',
'peace activist',
'guitar maker',
'musical instrument maker',
'bhikkhu',
'firefighter',
'bushi',
'conscientious objection',
'pacifist',
'theater director',
'electrician',
'altar server',
'inventor',
'ondist',
'catch trainer',
'ballet dancer',
'ballet master',
'diarist',
'security guard',
'assembly line worker',
'environmentalist',
'political activist',
'official',
'first lady',
'housekeeper',
'psychotherapist',
'prelate',
'chaplain',
'railroad construction foreman',
'ecologist',
'social worker',
'social activist',
'autobiographer',
'editor',
'game programmer',
'funeral director',
'curler',
'sprinter',
'veterinarian',
'music executive',
'costume designer',
'karateka',
'television producer',
'character animator',
'sound editor',
'trumpeter',
'columnist',
'canoeist',
'philologist',
'choir director',
'cardiac surgeon',
'terrorism',
'civil rights advocate',
'cross-country skier',
'minister',
'herpetologist',
'merchant',
'homekeeper',
'show jumper',
'zookeeper',
'primatologist',
'horse trainer',
'javelin thrower',
'archivist',
'paleontologist',
'pathologist',
'contributing editor',
'art critic',
'critic',
'pastor',
'long-distance runner',
'middle-distance runner',
'rancher',
'drug lord',
'trader',
'executioner',
'boatswain',
'watchmaker',
'car designer',
'microbiologist',
'virologist',
'pretender',
'executive',
'oceanographer',
'academic administrator',
'pentito',
'impresario',
'anthropologist',
'executive producer',
'legal scholar',
'patent inventor',
'criminologist',
'cowboy',
'ruler',
'mandolinist',
'radio producer',
'skipper',
'sociologist',
'steeplechase runner',
'founder',
'personal trainer',
'stripper',
'protestant reformer',
'trombonist',
'producer',
'music promoter',
'procurer',
'carpenter',
'promoter',
"corps de l'armement",
'technician',
'financier',
'rally driver',
'sex worker',
'lgbt rights activist',
'newspaper editor',
'thief',
'speleologist',
'handyman',
'feudatory',
'geheimrat',
'fashion model',
'diamond cutter',
'curator',
'bandleader',
'seiy?',
'illegal drug trade',
'racket',
'female guards in nazi concentration camps',
'psychoanalyst',
'french resistance fighter',
'bibliographer',
'rock drummer',
'ceramist',
'jazz pianist',
'penciller',
'plant physiology',
'oncologist',
'skydiver',
'kayaker',
'forensic psychiatrist',
'aikidoka',
'healer',
'herbalist',
'manual worker',
'casting director',
'fiddler',
'triple jumper',
'literary',
'bassist',
'baker',
'organizer',
'physiologist',
'islamistic terrorism',
'drafter',
'ornithologist',
'criminal sniper',
'functionary',
'daimyo',
'abolitionist',
'co-driver',
'glamour model',
'naturalist',
'stockbroker',
'combatant',
'suffragette',
'parson',
'suffragist',
'neurologist',
'land agent',
'rock climber',
'elevator operator',
'knight of the order of the temple',
'bobsledder',
'competitive diver',
'event rider',
'oboist',
'imam',
'clarinetist',
'real estate development',
'film critic',
'chief executive officer',
'pharmacologist',
'war correspondent',
'rabbi',
'double-bassist',
'postage stamp designer',
'printmaker',
'general practitioner',
'luger',
'fashion editor',
'felony',
'esperantist',
'news presenter',
'heilpraktiker',
'snowboarder',
'opera director',
'correspondent',
'consort',
'ballet pedagogue',
'highwayman',
'tribal chief',
'brother',
'weather presenter',
'mycologist',
'chief of police',
'scholar',
'mountain guide',
'classical philologist',
'governess',
'genealogist',
'reporter',
'theatrical producer',
'salesperson',
'chronicler',
'investigative reporter',
'ethologist',
'game author',
'criminality',
'rhetorician',
'dandy',
'harpsichordist',
'dance critic',
'artisan',
'puzzle designer',
'lobbyist',
'extortion',
'blacksmith',
'tailor',
'mobster',
'musicologist',
'ethnomusicologist',
'stunt performer',
'epidemiologist',
'paralegal',
'private investigator',
'secretary',
'interior designer',
'motocross rider',
'illusionist',
'harpist',
'child psychiatrist',
'test pilot',
'cadet',
'warrior',
'rakugoka',
'theatre manager',
'music critic',
'watercolourist',
'flight nurse',
'musher',
'ski mountaineer',
'lexicographer',
'televangelist',
'meteorologist',
'notary',
'volcanologist',
'conservator',
'breakdancer',
'statesperson',
'personal stylist',
'bookmaker',
'accordionist',
'bounty hunter',
'pioneer',
'corvette captain',
'ship captain',
'maid',
'lyricist',
'classical guitarist',
'social reformer',
'base jumper',
'governor',
'marksman',
'director',
'nightclub owner',
'industrialist',
'sexologist',
'memoirist',
'quizzer',
'endocrinologist',
'mountain biker',
'male prostitution',
'militant',
'latinist',
'mail carrier',
'matador',
'metallurgist',
'paratrooper',
'machinist',
'hotel manager',
'ufologist',
'ethnologist',
'castellan',
'butler',
'joiner',
'bank robber',
'lady-in-waiting',
'stunt pilot',
'animalier',
'encyclopédistes',
'cleric',
'law enforcement officer',
'forensic pathologist',
'strongman',
'taxi driver',
'antiquarian seller',
'rhythmic gymnast',
'folklorist',
'stand-up comedian',
'courtesan',
'cobbler',
'ascetic',
'pro gamer',
'dacoity',
'museum director',
'logician',
'miner',
'broadcaster',
'literary critic',
'theatre critic',
'scout',
'patient',
'grocer',
'bowler',
'equestrianism',
'equestrian',
'rheumatologist',
'dressage rider',
'calligrapher',
'christian mystic',
'neurosurgeon',
'justice of the peace',
'conservationist',
'go professional',
'spammer',
'assassin',
'mujahid',
'eye surgeon',
'histologist',
'street vendor',
'collector',
'winegrower',
'chamberlain',
'advertising person',
'rapping',
'heiress',
'peasant',
'prison warden',
'optician',
'bartender',
'mass murder',
'hurler',
'bushranger',
'bacteriologist',
'coroner',
'freemason',
'stunt double',
'hematologist',
'soprano',
'master builder',
'warlord',
'grand couturier',
'ice dancer',
'egyptologist',
'habitual offender',
'administrator of the government',
'abbé',
'bureaucrat',
'psychic',
'chief financial officer',
'chauffeur / chauffeuse',
'impostor',
'lumberjack',
'police',
'admiral',
'outlaw',
'astronaut',
'day trader',
'air force officer',
'jeweller',
'intellectual',
'guard',
'conservation',
'advocate',
'orator',
'stunt coordinator',
'freediver',
'general officer',
'carabinier',
'count',
'presenter',
'alderman',
'caricaturist',
'dressmaker',
'production manager',
'partisan',
'animal rights advocate',
'museum professional',
"aviation boatswain's mate",
'ethnographer',
'court reporter',
'gynaecologist',
'existential therapist',
'bouncer',
'assessor',
'miller',
'fighter',
'informant',
'arachnologist',
'sexual predator',
'librettist',
'carabinieri',
'patron of the arts',
'tutor',
'rebellion',
'intelligence agent',
'antiquarian',
'adventurer',
'ballerina',
'sniper',
'switchboard operator',
'rapist',
'dissident',
'political commissar',
'piracy',
'companion',
'captain',
'settler',
'organ builder',
'pasha',
'flower seller',
'crocheter',
'jesuit',
'art model',
'lighthouse keeper',
'topographer',
'etcher',
'engraver',
'squire',
'courtier',
'smuggler',
'fortune teller',
'poisoner',
'lord',
'mimus',
'lord of the manor',
'mass murderer',
'former comfort women',
'apothecary',
'fedayeen',
'docent',
'electronics technician',
'witch',
'bodyguard',
]



# setting custome tab
st.set_page_config(page_title='Lifespan prediction')


# ceating car model brand list.
# loading the dataset.
death = pd.read_csv('app_dataset.csv')


# loding the model
@st.cache(allow_output_mutation=True)
def model_loader(path):
    model = joblib.load(path)
    return model


# loading both models
with st.spinner('🚕🛺🚙🚜🚚🚓🚗🚕 Hold on, the app is loading !! 🚕🛺🚙🚜🚚🚓🚗🚕'):
    model_ridge = model_loader("model.pkl")




# # writing header
# st.title('# Used Car Price Predition™  🚗')
st.markdown("<h2 style='text-align: center;'>🚗  Lifespan prediction™  🚗</h2>", unsafe_allow_html=True)


col1, col2 = st.beta_columns(2)

country_inp = col1.selectbox(label='Enter the Country', options=country_list) # passing the brand list
country = country[country_inp] # converting the brand name to numerical encoding form

occ_inp = col1.selectbox(label='Enter the Occupation', options=occ_list) # passing the brand list
occ = country[country_inp] # converting the brand name to numerical encoding form

birthYear = col1.number_input(label='Enter the Birth year')
birthYear = int(birthYear)




# creatng a input array for prediction
inp_array = np.array([[birthYear,occ,country]])

predict = col1.button('Predict') # creating a predict buutton

if predict: 
        pred = model_ridge.predict(inp_array)
        if pred < 0: # handeling negative outputs.
            st.error('The input values must be irrelevant, try again by giving relevent information.')
        pred = int(pred)
        write = 'The predicted lifespan of this person is ¥ '+ str(pred) + ' 🚙' # showing the price prediction.
        st.success(write)
        st.balloons()


# writing some information about the projects.


